version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependabot
      - actions
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    labels:
      - dependabot
      - npm
    schedule:
      interval: daily
    groups:
      eslint:
        patterns:
          - "*eslint*"
